"""add_student_fields

Revision ID: 09e351d0cbb0
Revises: 925bf8cd9b7f
Create Date: 2026-05-14 00:19:54.837488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09e351d0cbb0'
down_revision: Union[str, Sequence[str], None] = '925bf8cd9b7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('university_id', sa.String(length=50), nullable=False))
    op.add_column('students', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('students', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('enrollment_date', sa.Date(), nullable=False))
    op.add_column('students', sa.Column('status', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_students_university_id'), 'students', ['university_id'], unique=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_students_university_id'), table_name='students')
    op.drop_column('students', 'status')
    op.drop_column('students', 'enrollment_date')
    op.drop_column('students', 'phone_number')
    op.drop_column('students', 'gender')
    op.drop_column('students', 'birth_date')
    op.drop_column('students', 'university_id')
    # ### end Alembic commands ###
